services:
  - type: web
    name: bom-transfer-professional
    env: static
    buildCommand: pnpm install --no-frozen-lockfile && pnpm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html